// Code generated by sqlc. DO NOT EDIT.
// source: elimsandwich.sql

package db

import (
	"context"
)

const createElimMaster = `-- name: CreateElimMaster :one
INSERT INTO  elim_unac_master (
  team_id,
  orders
) VALUES (
  $1, $2
) RETURNING id, team_id, orders, last_order, total_score, total_benar, total_salah, bos1_score, bos1_benar, bos1_salah, bos2_score, bos2_benar, bos2_salah, bos3_score, bos3_benar, bos3_salah, sthw_score, sthw_benar, sthw_salah, rtn_score, rtn_benar, rtn_salah
`

type CreateElimMasterParams struct {
	TeamID int32  `json:"team_id"`
	Orders string `json:"orders"`
}

func (q *Queries) CreateElimMaster(ctx context.Context, arg CreateElimMasterParams) (ElimUnacMaster, error) {
	row := q.db.QueryRowContext(ctx, createElimMaster, arg.TeamID, arg.Orders)
	var i ElimUnacMaster
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Orders,
		&i.LastOrder,
		&i.TotalScore,
		&i.TotalBenar,
		&i.TotalSalah,
		&i.Bos1Score,
		&i.Bos1Benar,
		&i.Bos1Salah,
		&i.Bos2Score,
		&i.Bos2Benar,
		&i.Bos2Salah,
		&i.Bos3Score,
		&i.Bos3Benar,
		&i.Bos3Salah,
		&i.SthwScore,
		&i.SthwBenar,
		&i.SthwSalah,
		&i.RtnScore,
		&i.RtnBenar,
		&i.RtnSalah,
	)
	return i, err
}

const createElimSandwich = `-- name: CreateElimSandwich :one
INSERT INTO  battle_of_sandwich_master (
  team_id,
  token,
  orders,
  paket
) VALUES (
  $1, $2, $3, $4
) RETURNING id, team_id, token, orders, paket, last_page, benar, salah, score
`

type CreateElimSandwichParams struct {
	TeamID int32  `json:"team_id"`
	Token  string `json:"token"`
	Orders string `json:"orders"`
	Paket  int32  `json:"paket"`
}

func (q *Queries) CreateElimSandwich(ctx context.Context, arg CreateElimSandwichParams) (BattleOfSandwichMaster, error) {
	row := q.db.QueryRowContext(ctx, createElimSandwich,
		arg.TeamID,
		arg.Token,
		arg.Orders,
		arg.Paket,
	)
	var i BattleOfSandwichMaster
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Token,
		&i.Orders,
		&i.Paket,
		&i.LastPage,
		&i.Benar,
		&i.Salah,
		&i.Score,
	)
	return i, err
}

const createElimSandwichJawaban = `-- name: CreateElimSandwichJawaban :exec
INSERT INTO battle_of_sandwich_jawaban (
  team_id,
  soal_id,
  jawaban
) VALUES (
  $1, $2, $3
)
ON CONFLICT (team_id, soal_id)  DO UPDATE SET jawaban = EXCLUDED.jawaban
`

type CreateElimSandwichJawabanParams struct {
	TeamID  int32  `json:"team_id"`
	SoalID  int32  `json:"soal_id"`
	Jawaban string `json:"jawaban"`
}

func (q *Queries) CreateElimSandwichJawaban(ctx context.Context, arg CreateElimSandwichJawabanParams) error {
	_, err := q.db.ExecContext(ctx, createElimSandwichJawaban, arg.TeamID, arg.SoalID, arg.Jawaban)
	return err
}

const getElimMasterByTeamId = `-- name: GetElimMasterByTeamId :one
SELECT id, team_id, orders, last_order, total_score, total_benar, total_salah, bos1_score, bos1_benar, bos1_salah, bos2_score, bos2_benar, bos2_salah, bos3_score, bos3_benar, bos3_salah, sthw_score, sthw_benar, sthw_salah, rtn_score, rtn_benar, rtn_salah from elim_unac_master
WHERE team_id = $1
`

func (q *Queries) GetElimMasterByTeamId(ctx context.Context, teamID int32) (ElimUnacMaster, error) {
	row := q.db.QueryRowContext(ctx, getElimMasterByTeamId, teamID)
	var i ElimUnacMaster
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Orders,
		&i.LastOrder,
		&i.TotalScore,
		&i.TotalBenar,
		&i.TotalSalah,
		&i.Bos1Score,
		&i.Bos1Benar,
		&i.Bos1Salah,
		&i.Bos2Score,
		&i.Bos2Benar,
		&i.Bos2Salah,
		&i.Bos3Score,
		&i.Bos3Benar,
		&i.Bos3Salah,
		&i.SthwScore,
		&i.SthwBenar,
		&i.SthwSalah,
		&i.RtnScore,
		&i.RtnBenar,
		&i.RtnSalah,
	)
	return i, err
}

const getElimSandwichById = `-- name: GetElimSandwichById :one
SELECT id, soal, pilihan1, pilihan2, pilihan3, pilihan4, jawaban, bobot, paket from elim_unac_battle_of_sandwich
WHERE id = $1
`

func (q *Queries) GetElimSandwichById(ctx context.Context, id int32) (ElimUnacBattleOfSandwich, error) {
	row := q.db.QueryRowContext(ctx, getElimSandwichById, id)
	var i ElimUnacBattleOfSandwich
	err := row.Scan(
		&i.ID,
		&i.Soal,
		&i.Pilihan1,
		&i.Pilihan2,
		&i.Pilihan3,
		&i.Pilihan4,
		&i.Jawaban,
		&i.Bobot,
		&i.Paket,
	)
	return i, err
}

const getElimSandwichByTeamId = `-- name: GetElimSandwichByTeamId :one
SELECT id, team_id, token, orders, paket, last_page, benar, salah, score from battle_of_sandwich_master
WHERE team_id = $1
AND token = $2
`

type GetElimSandwichByTeamIdParams struct {
	TeamID int32  `json:"team_id"`
	Token  string `json:"token"`
}

func (q *Queries) GetElimSandwichByTeamId(ctx context.Context, arg GetElimSandwichByTeamIdParams) (BattleOfSandwichMaster, error) {
	row := q.db.QueryRowContext(ctx, getElimSandwichByTeamId, arg.TeamID, arg.Token)
	var i BattleOfSandwichMaster
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Token,
		&i.Orders,
		&i.Paket,
		&i.LastPage,
		&i.Benar,
		&i.Salah,
		&i.Score,
	)
	return i, err
}

const getPageElimSandwich = `-- name: GetPageElimSandwich :one
SELECT last_page FROM battle_of_sandwich_master
WHERE team_id = $1
`

func (q *Queries) GetPageElimSandwich(ctx context.Context, teamID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getPageElimSandwich, teamID)
	var last_page int32
	err := row.Scan(&last_page)
	return last_page, err
}

const updatePageElimSandwich = `-- name: UpdatePageElimSandwich :exec
UPDATE battle_of_sandwich_master
SET last_page = last_page + 1
WHERE team_id = $1
`

func (q *Queries) UpdatePageElimSandwich(ctx context.Context, teamID int32) error {
	_, err := q.db.ExecContext(ctx, updatePageElimSandwich, teamID)
	return err
}

const updateSubmitedElimSandwich = `-- name: UpdateSubmitedElimSandwich :exec
UPDATE battle_of_sandwich_master
SET submited = now()
WHERE team_id = $1
`

func (q *Queries) UpdateSubmitedElimSandwich(ctx context.Context, teamID int32) error {
	_, err := q.db.ExecContext(ctx, updateSubmitedElimSandwich, teamID)
	return err
}
