// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type User struct {
	ID           int32          `json:"id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Username     string         `json:"username"`
	Password     string         `json:"password"`
	RefreshToken sql.NullString `json:"refresh_token"`
}
