// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	AddTeamIdToUser(ctx context.Context, arg AddTeamIdToUserParams) error
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	GetMemberById(ctx context.Context, id int32) (Member, error)
	GetMemberByTeamId(ctx context.Context, teamID int32) ([]Member, error)
	GetTeamById(ctx context.Context, id int32) (Team, error)
	GetTeamsPagination(ctx context.Context, arg GetTeamsPaginationParams) ([]Team, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error)
	SetRefreshToken(ctx context.Context, arg SetRefreshTokenParams) error
	UpdateVerifiedStatus(ctx context.Context, verified Verification) error
}

var _ Querier = (*Queries)(nil)
