// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	AddTeamIdToUser(ctx context.Context, arg AddTeamIdToUserParams) error
	CreateElimMaster(ctx context.Context, teamID int32) (ElimUnacMaster, error)
	CreateElimSandwich(ctx context.Context, arg CreateElimSandwichParams) (BattleOfSandwichMaster, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreatePrelimTac(ctx context.Context, arg CreatePrelimTacParams) (PrelimTacMaster, error)
	CreatePrelimTacPgJawaban(ctx context.Context, arg CreatePrelimTacPgJawabanParams) error
	CreatePrelimUnac(ctx context.Context, arg CreatePrelimUnacParams) (PrelimUnacMaster, error)
	CreatePrelimUnacIsianJawaban(ctx context.Context, arg CreatePrelimUnacIsianJawabanParams) error
	CreatePrelimUnacPgJawaban(ctx context.Context, arg CreatePrelimUnacPgJawabanParams) error
	CreateRescueJawaban(ctx context.Context, arg CreateRescueJawabanParams) error
	CreateRescueMaster(ctx context.Context, arg CreateRescueMasterParams) (RescueTheNumberMaster, error)
	CreateSandwichJawaban(ctx context.Context, arg CreateSandwichJawabanParams) error
	CreateScratchJawaban(ctx context.Context, arg CreateScratchJawabanParams) error
	CreateScratchMaster(ctx context.Context, arg CreateScratchMasterParams) (ScratchTheHiddenWordsMaster, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	GetConfig(ctx context.Context) (Config, error)
	GetElimMasterByTeamId(ctx context.Context, teamID int32) (ElimUnacMaster, error)
	GetElimSandwichById(ctx context.Context, id int32) (ElimUnacBattleOfSandwich, error)
	GetElimSandwichByPaket(ctx context.Context, arg GetElimSandwichByPaketParams) (BattleOfSandwichMaster, error)
	GetElimSandwichByTeamId(ctx context.Context, arg GetElimSandwichByTeamIdParams) (BattleOfSandwichMaster, error)
	GetMemberById(ctx context.Context, id int32) (Member, error)
	GetMemberByTeamId(ctx context.Context, teamID int32) ([]Member, error)
	GetPageElimSandwich(ctx context.Context, teamID int32) (int32, error)
	GetPagePrelimTac(ctx context.Context, teamID int32) (int32, error)
	GetPagePrelimUnac(ctx context.Context, teamID int32) (int32, error)
	GetPageSandwich(ctx context.Context, arg GetPageSandwichParams) (int32, error)
	GetPrelimTacByTeamId(ctx context.Context, teamID int32) (PrelimTacMaster, error)
	GetPrelimTacPgById(ctx context.Context, id int32) (PrelimTacPg, error)
	GetPrelimUnacByTeamId(ctx context.Context, teamID int32) (PrelimUnacMaster, error)
	GetPrelimUnacIsianById(ctx context.Context, id int32) (PrelimUnacIsian, error)
	GetPrelimUnacPgById(ctx context.Context, id int32) (PrelimUnacPg, error)
	GetRescueByTeamId(ctx context.Context, teamID int32) (RescueTheNumberMaster, error)
	GetRescueSoal(ctx context.Context) ([]ElimUnacRescueTheNumber, error)
	GetSandwichPg(ctx context.Context, id int32) (ElimUnacBattleOfSandwich, error)
	GetSandwichPgIdByPaket(ctx context.Context, paket int32) ([]int32, error)
	GetScratchByTeamId(ctx context.Context, teamID int32) (ScratchTheHiddenWordsMaster, error)
	GetScratchSoal(ctx context.Context) ([]ElimUnacScratchTheHiddenWord, error)
	GetTacPgIdByPaket(ctx context.Context, paket int32) ([]int32, error)
	GetTeamById(ctx context.Context, id int32) (Team, error)
	GetTeamsPagination(ctx context.Context, arg GetTeamsPaginationParams) ([]Team, error)
	GetUnacIsianIdByPaket(ctx context.Context, paket int32) ([]int32, error)
	GetUnacPgIdByPaket(ctx context.Context, paket int32) ([]int32, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error)
	SetRefreshToken(ctx context.Context, arg SetRefreshTokenParams) error
	UpdateElimStatus(ctx context.Context, arg UpdateElimStatusParams) error
	UpdatePageElimSandwich(ctx context.Context, teamID int32) error
	UpdatePagePrelimTac(ctx context.Context, teamID int32) error
	UpdatePagePrelimUnac(ctx context.Context, teamID int32) error
	UpdatePageSandwich(ctx context.Context, arg UpdatePageSandwichParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePaymentPrelimTac(ctx context.Context, arg UpdatePaymentPrelimTacParams) error
	UpdatePaymentPrelimUnac(ctx context.Context, arg UpdatePaymentPrelimUnacParams) error
	UpdatePaymentStatusPrelimTac(ctx context.Context, arg UpdatePaymentStatusPrelimTacParams) error
	UpdatePaymentStatusPrelimUnac(ctx context.Context, arg UpdatePaymentStatusPrelimUnacParams) error
	UpdatePrelimStatus(ctx context.Context, arg UpdatePrelimStatusParams) error
	UpdateRescueStatus(ctx context.Context, arg UpdateRescueStatusParams) error
	UpdateSandwichAStatus(ctx context.Context, arg UpdateSandwichAStatusParams) error
	UpdateSandwichBStatus(ctx context.Context, arg UpdateSandwichBStatusParams) error
	UpdateSandwichCStatus(ctx context.Context, arg UpdateSandwichCStatusParams) error
	UpdateScratchStatus(ctx context.Context, arg UpdateScratchStatusParams) error
	UpdateSubmitedElimSandwich(ctx context.Context, teamID int32) error
	UpdateSubmitedPrelimTac(ctx context.Context, teamID int32) error
	UpdateSubmitedPrelimUnac(ctx context.Context, teamID int32) error
	UpdateSubmitedRescue(ctx context.Context, teamID int32) error
	UpdateSubmitedSandwich(ctx context.Context, arg UpdateSubmitedSandwichParams) error
	UpdateSubmitedScratch(ctx context.Context, teamID int32) error
	UpdateVerifiedStatus(ctx context.Context, arg UpdateVerifiedStatusParams) error
}

var _ Querier = (*Queries)(nil)
