// Code generated by sqlc. DO NOT EDIT.
// source: tim.sql

package db

import (
	"context"
	"database/sql"
)

const createTim = `-- name: CreateTim :one
INSERT INTO tim (
  team_name,
  university,
  full_name,
  phone,
  id_line,
  email,
  photo_link,
  payment_link,
  card_link,
  sk_link,
  type
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, team_name, university, full_name, phone, id_line, email, photo_link, payment_link, card_link, sk_link, type, verified
`

type CreateTimParams struct {
	TeamName    string         `json:"team_name"`
	University  string         `json:"university"`
	FullName    string         `json:"full_name"`
	Phone       string         `json:"phone"`
	IDLine      string         `json:"id_line"`
	Email       string         `json:"email"`
	PhotoLink   string         `json:"photo_link"`
	PaymentLink string         `json:"payment_link"`
	CardLink    string         `json:"card_link"`
	SkLink      sql.NullString `json:"sk_link"`
	Type        Competition    `json:"type"`
}

func (q *Queries) CreateTim(ctx context.Context, arg CreateTimParams) (Tim, error) {
	row := q.db.QueryRowContext(ctx, createTim,
		arg.TeamName,
		arg.University,
		arg.FullName,
		arg.Phone,
		arg.IDLine,
		arg.Email,
		arg.PhotoLink,
		arg.PaymentLink,
		arg.CardLink,
		arg.SkLink,
		arg.Type,
	)
	var i Tim
	err := row.Scan(
		&i.ID,
		&i.TeamName,
		&i.University,
		&i.FullName,
		&i.Phone,
		&i.IDLine,
		&i.Email,
		&i.PhotoLink,
		&i.PaymentLink,
		&i.CardLink,
		&i.SkLink,
		&i.Type,
		&i.Verified,
	)
	return i, err
}

const getTimById = `-- name: GetTimById :one
SELECT id, team_name, university, full_name, phone, id_line, email, photo_link, payment_link, card_link, sk_link, type, verified FROM tim
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTimById(ctx context.Context, id int32) (Tim, error) {
	row := q.db.QueryRowContext(ctx, getTimById, id)
	var i Tim
	err := row.Scan(
		&i.ID,
		&i.TeamName,
		&i.University,
		&i.FullName,
		&i.Phone,
		&i.IDLine,
		&i.Email,
		&i.PhotoLink,
		&i.PaymentLink,
		&i.CardLink,
		&i.SkLink,
		&i.Type,
		&i.Verified,
	)
	return i, err
}
